ALTER TABLE public.contactos
ADD COLUMN IF NOT EXISTS catalogo_digital BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS catalogo_fisico BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS presupuesto_enviado BOOLEAN DEFAULT FALSE;

ALTER TABLE public.contactos_sandbox
ADD COLUMN IF NOT EXISTS catalogo_digital BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS catalogo_fisico BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS presupuesto_enviado BOOLEAN DEFAULT FALSE;
